In [3]:
import numpy as np 

tableau = np.array([1, 3, 5, 19])

print(tableau)


[ 1  3  5 19]


In [4]:
#Afiicher la taille du tableau 

print(tableau.size)

4


In [6]:
tableau.ndim


1

In [8]:
tableau.shape

(4,)

In [11]:
#Remplir le tableau des 0 

zeros = np.zeros((2, 3))

print(zeros)

In [12]:
zeros.ndim

2

In [13]:
zeros.shape


(2, 3)

In [15]:
ones = np.ones((4, 6))

print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [17]:
full = np.full((3, 5), 5)

print(full)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [20]:
rand = np.random.randn(5, 3)

print(rand)

[[-0.39339945 -0.90076153 -1.3763363 ]
 [-0.95056086  1.19562395  0.15633802]
 [-0.87005688 -0.00612542 -0.22757805]
 [ 0.44274001 -0.02288389  1.18803831]
 [ 0.13358904  1.45657564  1.02510565]]


In [21]:
np.linspace(3, -5, 20)

array([ 3.        ,  2.57894737,  2.15789474,  1.73684211,  1.31578947,
        0.89473684,  0.47368421,  0.05263158, -0.36842105, -0.78947368,
       -1.21052632, -1.63157895, -2.05263158, -2.47368421, -2.89473684,
       -3.31578947, -3.73684211, -4.15789474, -4.57894737, -5.        ])

In [24]:
np.arange(-3, 4, 1)

array([-3, -2, -1,  0,  1,  2,  3])

Manipulation 

In [35]:
A = np.ones((3, 5))
print(A)

B = np.zeros((3, 5))
print(B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
C = np.hstack((A, B))
print(C)
C.shape


[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]


(3, 10)

In [39]:
D = np.vstack((A, B))
print(D)
D.shape

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(6, 5)

In [41]:
E = np.concatenate((A, B), axis=1)
print(E)
E.shape

[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]


(3, 10)

In [42]:
E = np.concatenate((A, B), axis=0)
print(E)
E.shape

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(6, 5)

In [47]:
F = E.reshape((10,3))

print(F)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [51]:
tableau.shape
tableau = tableau.reshape((tableau.shape[0], 1))

In [53]:
tableau.shape

(4, 1)